# Generated by Django 6.0.5 on 2026-06-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_document_last_activity_document_last_activity_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='escalation_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🟠 High'), ('urgent', '🔴 Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('assignment', 'Assignment'), ('reminder', 'Reminder'), ('system', 'System'), ('status_update', 'Status Update'), ('escalation', 'Escalation')], default='system', max_length=20),
        ),
    ]
