# Generated by Django 6.0.5 on 2026-07-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_document_escalated_at_document_escalation_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
